baseurl = "http://dpc.pw/"
languageCode = "en-us"
title = "dpc's blog"
theme = "hugo-theme-puremose"
footnotereturnlinkcontents= "↩"
paginate = 10
disqusShortname = "dpc-blog"

[permalinks]
  post = "/:title/"

[params]
  description = "Random posts about stuff."
